<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

namespace Google;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Google.Request</code>
 */
class Request extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string controller = 1;</code>
     */
    protected $controller = '';
    /**
     * Generated from protobuf field <code>string method = 2;</code>
     */
    protected $method = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.Any req = 3;</code>
     */
    protected $req = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $controller
     *     @type string $method
     *     @type \Google\Protobuf\Any $req
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string controller = 1;</code>
     * @return string
     */
    public function getController()
    {
        return $this->controller;
    }

    /**
     * Generated from protobuf field <code>string controller = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setController($var)
    {
        GPBUtil::checkString($var, True);
        $this->controller = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string method = 2;</code>
     * @return string
     */
    public function getMethod()
    {
        return $this->method;
    }

    /**
     * Generated from protobuf field <code>string method = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMethod($var)
    {
        GPBUtil::checkString($var, True);
        $this->method = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Any req = 3;</code>
     * @return \Google\Protobuf\Any
     */
    public function getReq()
    {
        return isset($this->req) ? $this->req : null;
    }

    public function hasReq()
    {
        return isset($this->req);
    }

    public function clearReq()
    {
        unset($this->req);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Any req = 3;</code>
     * @param \Google\Protobuf\Any $var
     * @return $this
     */
    public function setReq($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Any::class);
        $this->req = $var;

        return $this;
    }

}

