<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

namespace Google;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Google.ResultException</code>
 */
class ResultException extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string className = 1;</code>
     */
    protected $className = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $className
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string className = 1;</code>
     * @return string
     */
    public function getClassName()
    {
        return $this->className;
    }

    /**
     * Generated from protobuf field <code>string className = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setClassName($var)
    {
        GPBUtil::checkString($var, True);
        $this->className = $var;

        return $this;
    }

}

