<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

namespace GPBMetadata;

class Common
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Any::initOnce();
        $pool->internalAddGeneratedFile(
            '
ç
common.protoGoogle"P
Request

controller (	
method (	!
req (2.google.protobuf.Any"O
Response
success (
info (	$
result (2.google.protobuf.Any"$
ResultException
	className (	bproto3'
        , true);

        static::$is_initialized = true;
    }
}

