<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: register.proto

namespace GPBMetadata;

class Register
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
o
register.protoGoogle"M
RegisterRequest
username (	
password (	
passwordRepeat (	bproto3'
        , true);

        static::$is_initialized = true;
    }
}

